language: python

python:
  - "2.7"
  - "3.6"
  - "3.8"

install:
  - pip install numpy pyparsing pytest pytest-cov
  - pip install .

script:
  - pytest
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then make -j 4 -C doc/sphinx SPHINXOPTS="-W --keep-going" html; fi
