name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: [3.8]
        doc: [1]
        #cfg:
        #  - { os: ubuntu-latest, py: 2.7 }
        #  - { os: ubuntu-latest, py: 3.6 }
        #  - { os: ubuntu-latest, py: 3.9, doc: 1 }
        #  - { os: windows-latest, py: 3.9 }
        #  - { os: macos-latest, py: 3.9 }

    steps:
    #- name: Add debugging
    #  uses: actions/debug-action@559167ee1cb13c2c18a0fdd94850d6b5139ec133

    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.py }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        python -m pip install numpy scipy matplotlib docutils pytest pytest-cov sphinx

    - name: Test with pytest
      run: |
        pytest -v

    - name: check that the docs build (linux only)
      if: matrix.doc == 1
      run: |
        make -j 4 -C doc/sphinx SPHINXOPTS="-W --keep-going" html